package me.eluch.libgdx.DoJuMu.game;

public enum Effect {

	NOTHING,
	COMMON_JUMP_CAUSER,
	MONSTER_HIT,
	BLACK_HOLE_HIT,
	SPRING_JUMP,
	TRAMPOLINE_JUMP,
	SPRING_SHOE_EQUIPPING,
	PROPELLER_HAT_EQUIPPING,
	JETPACK_EQUIPPING,
	SHIELD_EQUIPPING,
	PORTALLING,
	REVERSE_THE_OTHERS,
	SLOW_THE_OTHERS,
	
}
